//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.35312
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace tweetyzard.winform.LocalResources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class PrintFormatting {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal PrintFormatting() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("tweetyzard.winform.LocalResources.PrintFormatting", typeof(PrintFormatting).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to FFFFFFFF.
        /// </summary>
        internal static string ExcelCellFillColor {
            get {
                return ResourceManager.GetString("ExcelCellFillColor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Verdana.
        /// </summary>
        internal static string ExcelCellFont {
            get {
                return ResourceManager.GetString("ExcelCellFont", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 8.
        /// </summary>
        internal static string ExcelCellFontSize {
            get {
                return ResourceManager.GetString("ExcelCellFontSize", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 0084B4.
        /// </summary>
        internal static string ExcelColumnHeaderFillColor {
            get {
                return ResourceManager.GetString("ExcelColumnHeaderFillColor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Verdana.
        /// </summary>
        internal static string ExcelHeaderFont {
            get {
                return ResourceManager.GetString("ExcelHeaderFont", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to White.
        /// </summary>
        internal static string FilterOffButtonBackground {
            get {
                return ResourceManager.GetString("FilterOffButtonBackground", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to #6D6E71.
        /// </summary>
        internal static string FilterOffButtonBackgroundSwitch {
            get {
                return ResourceManager.GetString("FilterOffButtonBackgroundSwitch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to LightGrey.
        /// </summary>
        internal static string FilterOffButtonText {
            get {
                return ResourceManager.GetString("FilterOffButtonText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to White.
        /// </summary>
        internal static string FilterOffButtonTextSwitch {
            get {
                return ResourceManager.GetString("FilterOffButtonTextSwitch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to #6D6E71.
        /// </summary>
        internal static string FilterOnButtonBackground {
            get {
                return ResourceManager.GetString("FilterOnButtonBackground", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to White.
        /// </summary>
        internal static string FilterOnButtonBackgroundSwitch {
            get {
                return ResourceManager.GetString("FilterOnButtonBackgroundSwitch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to White.
        /// </summary>
        internal static string FilterOnButtonText {
            get {
                return ResourceManager.GetString("FilterOnButtonText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to LightGray.
        /// </summary>
        internal static string FilterOnButtonTextSwitch {
            get {
                return ResourceManager.GetString("FilterOnButtonTextSwitch", resourceCulture);
            }
        }
    }
}
