//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.35312
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TweetinviControllers.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("TweetinviControllers.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to https://api.twitter.com/1.1/account/settings.json.
        /// </summary>
        internal static string Account_GetSettings {
            get {
                return ResourceManager.GetString("Account_GetSettings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to https://api.twitter.com/1.1/friendships/create.json?{0}.
        /// </summary>
        internal static string Friendship_Create {
            get {
                return ResourceManager.GetString("Friendship_Create", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to https://api.twitter.com/1.1/friendships/destroy.json?{0}.
        /// </summary>
        internal static string Friendship_Destroy {
            get {
                return ResourceManager.GetString("Friendship_Destroy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to https://api.twitter.com/1.1/friendships/incoming.json?.
        /// </summary>
        internal static string Friendship_GetIncomingIds {
            get {
                return ResourceManager.GetString("Friendship_GetIncomingIds", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to https://api.twitter.com/1.1/friendships/outgoing.json?.
        /// </summary>
        internal static string Friendship_GetOutgoingIds {
            get {
                return ResourceManager.GetString("Friendship_GetOutgoingIds", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to https://api.twitter.com/1.1/friendships/update.json?retweets={0}&amp;device={1}&amp;{2}.
        /// </summary>
        internal static string Friendship_Update {
            get {
                return ResourceManager.GetString("Friendship_Update", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to long={0}&amp;lat={1}.
        /// </summary>
        internal static string Geo_CoordinatesParameter {
            get {
                return ResourceManager.GetString("Geo_CoordinatesParameter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to https://api.twitter.com/1.1/geo/id/{0}.json.
        /// </summary>
        internal static string Geo_GetPlaceFromId {
            get {
                return ResourceManager.GetString("Geo_GetPlaceFromId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to place_id={0}.
        /// </summary>
        internal static string Geo_PlaceIdParameter {
            get {
                return ResourceManager.GetString("Geo_PlaceIdParameter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to https://api.twitter.com/1.1/application/rate_limit_status.json.
        /// </summary>
        internal static string Help_GetRateLimit {
            get {
                return ResourceManager.GetString("Help_GetRateLimit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to https://api.twitter.com/1.1/help/privacy.json.
        /// </summary>
        internal static string Help_GetTwitterPrivacyPolicy {
            get {
                return ResourceManager.GetString("Help_GetTwitterPrivacyPolicy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &amp;description={0}.
        /// </summary>
        internal static string List_DescriptionParameter {
            get {
                return ResourceManager.GetString("List_DescriptionParameter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to https://api.twitter.com/1.1/lists/destroy.json?{0}.
        /// </summary>
        internal static string List_Destroy {
            get {
                return ResourceManager.GetString("List_Destroy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to https://api.twitter.com/1.1/lists/statuses.json?{0}.
        /// </summary>
        internal static string List_GetTweetsFromList {
            get {
                return ResourceManager.GetString("List_GetTweetsFromList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to https://api.twitter.com/1.1/lists/list.json?{0}&amp;reverse={1}.
        /// </summary>
        internal static string List_GetUserLists {
            get {
                return ResourceManager.GetString("List_GetUserLists", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &amp;list_id={0}.
        /// </summary>
        internal static string List_ListIdParameter {
            get {
                return ResourceManager.GetString("List_ListIdParameter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to https://api.twitter.com/1.1/lists/members.json?{0}.
        /// </summary>
        internal static string List_Members {
            get {
                return ResourceManager.GetString("List_Members", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &amp;name={0}.
        /// </summary>
        internal static string List_NameParameter {
            get {
                return ResourceManager.GetString("List_NameParameter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &amp;owner_id={0}.
        /// </summary>
        internal static string List_OwnerIdParameter {
            get {
                return ResourceManager.GetString("List_OwnerIdParameter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &amp;owner_screen_name={0}.
        /// </summary>
        internal static string List_OwnerScreenNameParameter {
            get {
                return ResourceManager.GetString("List_OwnerScreenNameParameter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &amp;mode={0}.
        /// </summary>
        internal static string List_PrivacyModeParameter {
            get {
                return ResourceManager.GetString("List_PrivacyModeParameter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &amp;slug={0}.
        /// </summary>
        internal static string List_SlugParameter {
            get {
                return ResourceManager.GetString("List_SlugParameter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to https://api.twitter.com/1.1/lists/update.json?{0}.
        /// </summary>
        internal static string List_Update {
            get {
                return ResourceManager.GetString("List_Update", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to https://api.twitter.com/1.1/direct_messages/destroy.json?id={0}.
        /// </summary>
        internal static string Message_DestroyMessage {
            get {
                return ResourceManager.GetString("Message_DestroyMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to https://api.twitter.com/1.1/direct_messages.json?count={0}.
        /// </summary>
        internal static string Message_GetMessagesReceived {
            get {
                return ResourceManager.GetString("Message_GetMessagesReceived", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to https://api.twitter.com/1.1/direct_messages/new.json?text={0}&amp;{1}.
        /// </summary>
        internal static string Message_NewMessage {
            get {
                return ResourceManager.GetString("Message_NewMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to https://api.twitter.com/1.1/direct_messages/sent.json?count={0}.
        /// </summary>
        internal static string Messages_GetMessagesSent {
            get {
                return ResourceManager.GetString("Messages_GetMessagesSent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &amp;count={0}.
        /// </summary>
        internal static string QueryParameter_Count {
            get {
                return ResourceManager.GetString("QueryParameter_Count", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &amp;max_id={0}.
        /// </summary>
        internal static string QueryParameter_MaxId {
            get {
                return ResourceManager.GetString("QueryParameter_MaxId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &amp;since_id={0}.
        /// </summary>
        internal static string QueryParameter_SinceId {
            get {
                return ResourceManager.GetString("QueryParameter_SinceId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to https://api.twitter.com/1.1/saved_searches/destroy/{0}.json.
        /// </summary>
        internal static string SavedSearch_Destroy {
            get {
                return ResourceManager.GetString("SavedSearch_Destroy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to https://api.twitter.com/1.1/saved_searches/list.json.
        /// </summary>
        internal static string SavedSearches_GetList {
            get {
                return ResourceManager.GetString("SavedSearches_GetList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to https://api.twitter.com/1.1/search/tweets.json?q={0}.
        /// </summary>
        internal static string Search_SearchTweets {
            get {
                return ResourceManager.GetString("Search_SearchTweets", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &amp;geocode={0}%2C{1}%2C{2}{3}.
        /// </summary>
        internal static string SearchParameter_GeoCode {
            get {
                return ResourceManager.GetString("SearchParameter_GeoCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &amp;lang={0}.
        /// </summary>
        internal static string SearchParameter_Lang {
            get {
                return ResourceManager.GetString("SearchParameter_Lang", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &amp;locale={0}.
        /// </summary>
        internal static string SearchParameter_Locale {
            get {
                return ResourceManager.GetString("SearchParameter_Locale", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &amp;result_type={0}.
        /// </summary>
        internal static string SearchParameter_ResultType {
            get {
                return ResourceManager.GetString("SearchParameter_ResultType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &amp;until={0}.
        /// </summary>
        internal static string SearchParameter_Until {
            get {
                return ResourceManager.GetString("SearchParameter_Until", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to https://api.twitter.com/1.1/statuses/home_timeline.json?include_entities=true&amp;count={0}&amp;exclude_replies={1}.
        /// </summary>
        internal static string Timeline_GetHomeTimeline {
            get {
                return ResourceManager.GetString("Timeline_GetHomeTimeline", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to https://api.twitter.com/1.1/statuses/mentions_timeline.json?include_entities=true&amp;count={0}&amp;exclude_replies={1}.
        /// </summary>
        internal static string Timeline_GetMentionsTimeline {
            get {
                return ResourceManager.GetString("Timeline_GetMentionsTimeline", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to https://api.twitter.com/1.1/statuses/user_timeline.json?include_entities=true&amp;count={0}&amp;exclude_replies={1}.
        /// </summary>
        internal static string Timeline_GetUserTimeline {
            get {
                return ResourceManager.GetString("Timeline_GetUserTimeline", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to https://api.twitter.com/1.1/trends/place.json?id={0}.
        /// </summary>
        internal static string Trends_GetTrendsFromWoeId {
            get {
                return ResourceManager.GetString("Trends_GetTrendsFromWoeId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to https://api.twitter.com/1.1/statuses/destroy/{0}.json.
        /// </summary>
        internal static string Tweet_Destroy {
            get {
                return ResourceManager.GetString("Tweet_Destroy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to https://api.twitter.com/1.1/favorites/create.json?id={0}.
        /// </summary>
        internal static string Tweet_Favorite_Create {
            get {
                return ResourceManager.GetString("Tweet_Favorite_Create", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to https://api.twitter.com/1.1/favorites/destroy.json?id={0}.
        /// </summary>
        internal static string Tweet_Favorite_Destroy {
            get {
                return ResourceManager.GetString("Tweet_Favorite_Destroy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to https://api.twitter.com/1.1/statuses/oembed.json?id={0}.
        /// </summary>
        internal static string Tweet_GenerateOEmbed {
            get {
                return ResourceManager.GetString("Tweet_GenerateOEmbed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to https://api.twitter.com/1.1/statuses/update.json?status={0}&amp;trim_user=true.
        /// </summary>
        internal static string Tweet_Publish {
            get {
                return ResourceManager.GetString("Tweet_Publish", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to https://api.twitter.com/1.1/statuses/update.json?status={0}&amp;in_reply_to_status_id={1}&amp;trim_user=true.
        /// </summary>
        internal static string Tweet_PublishInReplyTo {
            get {
                return ResourceManager.GetString("Tweet_PublishInReplyTo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to https://api.twitter.com/1.1/statuses/retweets/{0}.json.
        /// </summary>
        internal static string Tweet_Retweet_GetRetweets {
            get {
                return ResourceManager.GetString("Tweet_Retweet_GetRetweets", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to https://api.twitter.com/1.1/statuses/retweet/{0}.json?trim_user=true.
        /// </summary>
        internal static string Tweet_Retweet_Publish {
            get {
                return ResourceManager.GetString("Tweet_Retweet_Publish", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to https://api.twitter.com/1.1/blocks/create.json?{0}.
        /// </summary>
        internal static string User_Block_Create {
            get {
                return ResourceManager.GetString("User_Block_Create", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to https://api.twitter.com/1.1/favorites/list.json?{0}&amp;count={1}.
        /// </summary>
        internal static string User_GetFavourites {
            get {
                return ResourceManager.GetString("User_GetFavourites", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to https://api.twitter.com/1.1/followers/ids.json?{0}&amp;count={1}.
        /// </summary>
        internal static string User_GetFollowers {
            get {
                return ResourceManager.GetString("User_GetFollowers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to https://api.twitter.com/1.1/friends/ids.json?{0}&amp;count={1}.
        /// </summary>
        internal static string User_GetFriends {
            get {
                return ResourceManager.GetString("User_GetFriends", resourceCulture);
            }
        }
    }
}
